### ISSUE TITLE
Javascript messes up syntax highlighting

### ISSUE THREAD

**Issue by ti-font** [Bizcuit/vscode-ampscript#6] opened 2020-09-25 11:41 UTC
Hi Bizcuit,
First of: GREAT VS Code extension!

I noticed that a Javascript script section in a Cloud Page can mess up the syntax highlighting behind it.

I used:
`<script type="text/javascript">
 function optin_changed(optinCheckBox){
 if(optinCheckBox.checked){
        document.getElementById("submit").className = "btn";
    } else {
        document.getElementById("submit").className = "btn-disabled";
    }
 }
</script>`

The if() seems to be the cause. Maybe because it's recognized as AMPscript syntax? If I remove the if(), the highlighting returns to normal.

Thanks

**Comment by Bizcuit** [comment] 2020-09-25 18:19
Hi @ti-font 
Thanks a lot for your feedback. 
Regarding the issue. I can't reproduce it. Could you please share a screenshot that includes some HTML around your script tag? What happens if you switch from AMPScript syntax highlighting to standard VSCode HTML? 
Ampscript should be only highlighted inside %%[...]%% or %%=....=%%

**Comment by Bizcuit** [comment] 2020-10-07 16:42
@ti-font 
I am closing this issue, as I can't reproduce it. It would be great if you could share a full example of the file that has this problem, otherwise I will not be able to fix it.

**Closed** 2020-10-07 16:42 UTC
