### ISSUE TITLE
No able to see all content

### ISSUE THREAD

**Issue by teunardio** [Bizcuit/vscode-ampscript#9] opened 2020-11-20 13:04 UTC
We have quite a big collection of Cloudpages, Emails, Templates etc. When making the connection to our SFMC instance I only see a few of our Cloudpages and other content items. Any idea what the issue is here? Working in VScode on Mac OS.

**Comment by Bizcuit** [comment] 2020-11-22 19:46
Hey @teunardio 
I think I know the reason. Current version only renders first 100 assets in each folder. All cloudpages are located directly in the Content Builder folder. So if you have lot of assets in the root folder of Content Builder and lots of cloudpages, some of them will not be loaded by the extensions because of the limit. I guess you can see all assets in all other folders, right?

This will be fixed in the new version that is currently under development. New version will have a separate folder for CloudPages.

Please let me know if this "100 assets per folder" limit sounds like the root cause of your problem

**Comment by teunardio** [comment] 2020-11-23 19:51
@Bizcuit Yes, this is most probably the cause of the issue I'm facing. Looking forward to the updated repo.

**Comment by alejandro-martinez-hernandez** [comment] 2021-01-26 18:23
Hi  @Bizcuit 
About the Landing Pages, is it possible that the extension only retrieves the new? I've been able to observe that the Landing Pages marked with "Classic Editor" are not obtained

**Comment by Bizcuit** [comment] 2021-04-07 17:26
@alejandro-martinez-hernandez 
Unfortunately MC does not have official APIs to work with Classic landing pages. Therefore it is tricky to implement. I heard that some of the internal APIs will be available soon. I'll try to implement this functionality as soon as there is smth from the product team!

**Comment by Bizcuit** [comment] 2021-04-07 17:27
@teunardio
New version of the extension is now available on the market place. Cloudpages are now located in a separate folder + the item limit per folder is increase to 256. Hope it helps!

**Closed by Bizcuit** 2021-04-07 17:27 UTC
Labels: asap, enhancement
